import time
import sys
print("---------------")
name = input("player 1 name: ")
print ("player 1: " + name)
print("---------------")
name2 = input("player 2 name: ")
print ("player 2: " + name2)
print("---------------")

time.sleep(1)

print(name + " look away from the screen !!!")

time.sleep(2)

print(name2 + " Please enter a word for " + name + " to guess on the following line")

word = input ("Enter word to guess: ")
print("there will now be a generated gap, do not scroll up after this !!!")

print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
time.sleep(0.5)
print (name + " Can look at the screen again !")
time.sleep(1)


guess1 = input (name + " Guess a letter: ")
if guess1 in (word):
    print ("correct")
    G2()
        
else:
    print ("incorrect")




def H6():
    print("-------")
    print("|    |")
    print("|    O")
    print("|   /|\"")
    print("|   / \"")
    print("|")
    print("-------")

def H5():
    print("-------")
    print("|    |")
    print("|    O")
    print("|   /|\"")
    print("|   / ")
    print("|")
    print("-------")

def H4():
    print("-------")
    print("|    |")
    print("|    O")
    print("|   /|\"")
    print("|    ")
    print("|")
    print("-------")

def H3():
    print("-------")
    print("|    |")
    print("|    O")
    print("|   /|")
    print("|   ")
    print("|")
    print("-------")

def H2():
    print("-------")
    print("|    |")
    print("|    O")
    print("|    |")
    print("|   ")
    print("|")
    print("-------")

def H1():
    print("-------")
    print("|    |")
    print("|    O")
    print("|   ")
    print("|   ")
    print("|")
    print("-------")

def H0():
    print("-------")
    print("|    |")
    print("|    ")
    print("|   ")
    print("|   ")
    print("|")
    print("-------")

